### ISSUE TITLE
Plot with `theme_fivethirtyeight()` applied can't be further modified with `{ggplot2}` functions

### ISSUE THREAD

**Issue by IndrajeetPatil** [jrnold/ggthemes#138]
``` r
library(ggplot2)
library(ggthemes)

p <- ggplot(mtcars, aes(cyl, mpg)) + geom_point() 

# works
p + 
  theme_economist() +
  scale_y_continuous(name = "main", sec.axis = dup_axis(name = "secondary"))
```

![](https://i.imgur.com/zvOxTEy.png)

``` r

# works
p + 
  theme_gdocs() +
  scale_y_continuous(name = "main", sec.axis = dup_axis(name = "secondary"))
```

![](https://i.imgur.com/1yD39Uk.png)

``` r

# doesn't work
p + 
  theme_fivethirtyeight() + 
  scale_y_continuous(name = "main", sec.axis = dup_axis(name = "secondary"))
```

![](https://i.imgur.com/VpTmSuM.png)

<sup>Created on 2022-04-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by KayleeDavisGitHub** [comment]
I think this is intended given the `axis.text = element_text(),` present in the [fivethrityeight code](https://github.com/jrnold/ggthemes/blob/main/R/fivethirtyeight.R). Other themes do not have the element blank as you mentioned, but some themes have axis tick marks blank, titling blank, and other stuff too. For instance, in [economist.R](https://github.com/jrnold/ggthemes/blob/main/R/economist.R) you are unable to adjust the `panel.border` due to the designer setting that blank.

I'm not sure if this is a bug; I think it's an intended feature to keep the themes close to their source (FiveThirtyEight notoriously rarely ever adds axis labels). 

Also wanted to show that this isn't a dual-axis issue or an issue in how you've labeled the axis here, no titling works when using that theme for intended purposes:

```r
library(ggplot2)
library(ggthemes)
p <- ggplot(mtcars, aes(cyl, mpg)) + geom_point() 

# works
p + 
  theme_economist() +
  labs(y = "test",
         x = "test")

# works
p + 
  theme_gdocs() +
  labs(y = "test",
         x = "test")


# doesn't work
p +
  theme_fivethirtyeight() +
  labs(y = "test",
         x = "test") +
  xlab("test") + # These don't work either:
  ylab("test")
  ```

**Comment by IndrajeetPatil** [comment]
> I'm not sure if this is a bug; I think it's an intended feature to keep the themes close to their source (FiveThirtyEight notoriously rarely ever adds axis labels).

@KayleeDavisGitHub Thanks for the detailed explanation! Makes sense then that this doesn't work.

**Comment by KayleeDavisGitHub** [comment]
Happy to help @IndrajeetPatil ❤️ 
Thanks for all the work you've done for the R community!

For completeness here are some other resources if people are interested:

- This question was also asked here - #61 
- You can get around the theme and still add x/y labs [by doing this](https://stackoverflow.com/questions/36181990/add-ylab-to-ggplot-with-fivethirtyeight-ggtheme)
- Others have asked [this question](https://stackoverflow.com/questions/57751909/x-and-y-labels-not-appearing-on-my-ggplot) as well.
