### ISSUE TITLE
scale_colour with many levels

### ISSUE THREAD

**Issue by kferris10** [jrnold/ggthemes#43]
Do any of the `scale_colour_` options in this plot work for factors with many levels?  I can't seem to get it.

```
mtcars$id <- 1:nrow(mtcars)
qplot(wt, mpg, data = mtcars, colour = factor(id)) + scale_colour_discrete(guide = F)
```

![image](https://cloud.githubusercontent.com/assets/6612411/9373135/ccb1e3f2-46b4-11e5-82e8-afece8b9dff2.png)

```
qplot(wt, mpg, data = mtcars, colour = factor(id)) + scale_colour_hc(guide = F)
```

![image](https://cloud.githubusercontent.com/assets/6612411/9373145/e86b2252-46b4-11e5-8eb4-6b91afd7976a.png)

**Comment by jrnold** [comment]
None of the discrete color scales in this package have that many (32) colors.  A few like gdocs, tableau "cyclic" and "tableau20" have up to 20 colors. The scales in this package are generally manually specified rather than being generated from a formula like `scale_colour_discrete`. So they usually don't have much more than 10 colors.  There's not much purpose to using color as a dimension for a categorical variable with much more colors,  since they start to become visually indistinguishable with too many.
