### ISSUE TITLE
Suppression of axis labels

### ISSUE THREAD

**Issue by geotheory** [jrnold/ggthemes#66]
Thanks for these super neat themes. Small suggestion:

```
p = ggplot(iris, aes(Sepal.Width, Sepal.Length)) + geom_point(); p
p + theme_fivethirtyeight() + labs(x = 'Width', h = 'Length')
p + theme_wsj() + labs(x = 'Width', h = 'Length')
```

Is it possible to re-enable axis labels if they're specified?

**Comment by jrnold** [comment]
Yes. Since the ggplot2 themes are extensible, you can think of them as starting points rather than end points. Add `+ theme(...)` to the `ggplot` object to adjust whatever you'd like. See the [ggplot2 docs](http://docs.ggplot2.org/dev/vignettes/themes.html) on this for a much deeper explanation. In your case, here's how to add back axis titles,
```r
library("ggplot2")
library("ggthemes")


p <- ggplot(iris, aes(Sepal.Width, Sepal.Length)) + geom_point(); p
p + theme_fivethirtyeight() + theme(axis.title = element_text()) + labs(x = 'Width', h = 'Length')
p + theme_wsj() + theme(axis.title = element_text()) +  labs(x = 'Width', h = 'Length') 
```
